use crate::zone::models::{RiskLevel, RuleCategory};

/// Metadata definition for a security audit rule
#[derive(Debug, Clone)]
pub struct RuleDefinition {
    pub id: &'static str,
    pub name: &'static str,
    pub category: RuleCategory,
    pub default_severity: RiskLevel,
    pub title: &'static str,
    pub description: &'static str,
    pub remediation: &'static str,
    pub doc_url: &'static str,
}

pub const ALL_RULES: &[RuleDefinition] = &[
    RuleDefinition {
        id: "CF-SSL-001",
        name: "SSLModeCheck",
        category: RuleCategory::SslTls,
        default_severity: RiskLevel::Critical,
        title: "Insecure SSL/TLS Encryption Mode",
        description: "SSL mode is set to 'off' or 'flexible'. Flexible SSL does not encrypt traffic between Cloudflare edge servers and origin servers, exposing sensitive payload data to Man-In-The-Middle (MITM) attacks.",
        remediation: "Navigate to SSL/TLS > Overview in Cloudflare Dashboard and set SSL/TLS encryption mode to 'Full (strict)'. Ensure a valid SSL certificate is installed on the origin server.",
        doc_url: "https://developers.cloudflare.com/ssl/origin-configuration/ssl-modes/full-strict/",
    },
    RuleDefinition {
        id: "CF-SSL-002",
        name: "SSLNotStrict",
        category: RuleCategory::SslTls,
        default_severity: RiskLevel::Medium,
        title: "SSL/TLS Mode is Full (Non-Strict)",
        description: "SSL mode is set to 'full' instead of 'full (strict)'. Full mode does not validate the origin certificate against a trusted CA, leaving the connection susceptible to origin spoofing.",
        remediation: "Upgrade SSL/TLS mode to 'Full (strict)' after validating origin server certificates (Cloudflare Origin CA or public CA).",
        doc_url: "https://developers.cloudflare.com/ssl/origin-configuration/ssl-modes/full-strict/",
    },
    RuleDefinition {
        id: "CF-TLS-001",
        name: "MinimumTlsVersion",
        category: RuleCategory::SslTls,
        default_severity: RiskLevel::High,
        title: "Deprecated Minimum TLS Version (< 1.2)",
        description: "Minimum TLS version is set below TLS 1.2 (e.g. TLS 1.0 or 1.1). Legacy TLS protocols contain known cryptographic weaknesses (POODLE, BEAST) and fail PCI-DSS compliance.",
        remediation: "Go to SSL/TLS > Edge Certificates > Minimum TLS Version and select 'TLS 1.2' or 'TLS 1.3'.",
        doc_url: "https://developers.cloudflare.com/ssl/edge-certificates/minimum-tls-version/",
    },
    RuleDefinition {
        id: "CF-TLS-002",
        name: "Tls13Disabled",
        category: RuleCategory::SslTls,
        default_severity: RiskLevel::Low,
        title: "TLS 1.3 Protocol Disabled",
        description: "TLS 1.3 is disabled. TLS 1.3 provides significant latency improvements (0-RTT/1-RTT handshakes) and modern AEAD cipher suites.",
        remediation: "Enable TLS 1.3 under SSL/TLS > Edge Certificates > TLS 1.3 in the Cloudflare Dashboard.",
        doc_url: "https://developers.cloudflare.com/ssl/edge-certificates/additional-options/tls-13/",
    },
    RuleDefinition {
        id: "CF-HTTPS-001",
        name: "AlwaysUseHttps",
        category: RuleCategory::HttpsEnforcement,
        default_severity: RiskLevel::High,
        title: "Always Use HTTPS Disabled",
        description: "Unencrypted HTTP requests are not automatically redirected to HTTPS, allowing plaintext HTTP communication if requested by clients.",
        remediation: "Enable 'Always Use HTTPS' in SSL/TLS > Edge Certificates in Cloudflare Dashboard.",
        doc_url: "https://developers.cloudflare.com/ssl/edge-certificates/additional-options/always-use-https/",
    },
    RuleDefinition {
        id: "CF-HTTPS-002",
        name: "AutomaticHttpsRewrites",
        category: RuleCategory::HttpsEnforcement,
        default_severity: RiskLevel::Medium,
        title: "Automatic HTTPS Rewrites Disabled",
        description: "Automatic HTTPS rewrites is disabled, which may cause mixed-content warnings when HTTP resources are embedded in secure HTTPS pages.",
        remediation: "Enable 'Automatic HTTPS Rewrites' under SSL/TLS > Edge Certificates.",
        doc_url: "https://developers.cloudflare.com/ssl/edge-certificates/additional-options/automatic-https-rewrites/",
    },
    RuleDefinition {
        id: "CF-HSTS-001",
        name: "HstsDisabled",
        category: RuleCategory::Hsts,
        default_severity: RiskLevel::High,
        title: "HTTP Strict Transport Security (HSTS) Disabled",
        description: "HSTS header is not enabled for the zone. Without HSTS, browsers may allow initial unencrypted HTTP connections susceptible to SSL stripping attacks.",
        remediation: "Enable HSTS under SSL/TLS > Edge Certificates > HTTP Strict Transport Security (HSTS).",
        doc_url: "https://developers.cloudflare.com/ssl/edge-certificates/additional-options/http-strict-transport-security/",
    },
    RuleDefinition {
        id: "CF-HSTS-002",
        name: "HstsMaxAgeTooShort",
        category: RuleCategory::Hsts,
        default_severity: RiskLevel::Medium,
        title: "HSTS Max-Age Duration Too Short (< 6 Months)",
        description: "HSTS max-age duration is less than 15,552,000 seconds (6 months). A short max-age duration fails modern security baselines and HSTS preload requirements (minimum 1 year / 31,536,000s).",
        remediation: "Increase HSTS max-age to at least 6 months (15,552,000 seconds) or preferably 1 year (31,536,000 seconds) in HSTS settings.",
        doc_url: "https://developers.cloudflare.com/ssl/edge-certificates/additional-options/http-strict-transport-security/",
    },
    RuleDefinition {
        id: "CF-HSTS-003",
        name: "HstsIncludeSubdomainsMissing",
        category: RuleCategory::Hsts,
        default_severity: RiskLevel::Medium,
        title: "HSTS Include Subdomains Disabled",
        description: "HSTS does not apply to all subdomains (includeSubDomains is false). Unprotected subdomains remain vulnerable to downgrade attacks.",
        remediation: "Check 'Apply HSTS policy to subdomains (includeSubDomains)' in HSTS settings.",
        doc_url: "https://developers.cloudflare.com/ssl/edge-certificates/additional-options/http-strict-transport-security/",
    },
    RuleDefinition {
        id: "CF-HSTS-004",
        name: "HstsPreloadDisabled",
        category: RuleCategory::Hsts,
        default_severity: RiskLevel::Low,
        title: "HSTS Preload Directive Missing",
        description: "HSTS preload directive is not enabled. Without preloading, first-time site visitors are not protected by browser-baked HSTS lists.",
        remediation: "Enable 'Preload' in HSTS settings and submit the domain to hstspreload.org.",
        doc_url: "https://hstspreload.org/",
    },
    RuleDefinition {
        id: "CF-HSTS-005",
        name: "HstsNoSniffMissing",
        category: RuleCategory::Hsts,
        default_severity: RiskLevel::Low,
        title: "HSTS No-Sniff Header Disabled",
        description: "X-Content-Type-Options: nosniff header is disabled in HSTS security header configuration.",
        remediation: "Enable 'No-Sniff' in HSTS settings to prevent MIME type sniffing attacks.",
        doc_url: "https://developers.cloudflare.com/ssl/edge-certificates/additional-options/http-strict-transport-security/",
    },
    RuleDefinition {
        id: "CF-WAF-001",
        name: "WafManagedRulesDisabled",
        category: RuleCategory::WafSecurity,
        default_severity: RiskLevel::High,
        title: "WAF Managed Rulesets Inactive",
        description: "Cloudflare Web Application Firewall (WAF) managed rules are disabled or not configured. The zone lacks automated zero-day protection against OWASP Top 10 vulnerabilities.",
        remediation: "Enable Cloudflare Managed Ruleset and OWASP Core Ruleset under Security > WAF > Managed Rules.",
        doc_url: "https://developers.cloudflare.com/waf/managed-rules/",
    },
    RuleDefinition {
        id: "CF-BOT-001",
        name: "BotFightModeDisabled",
        category: RuleCategory::BotManagement,
        default_severity: RiskLevel::Medium,
        title: "Bot Fight Mode / Bot Protection Inactive",
        description: "Bot Fight Mode or Super Bot Fight Mode is disabled. Automated credential stuffing, scrapers, and malicious bot traffic are not actively mitigated.",
        remediation: "Enable 'Bot Fight Mode' under Security > Bots in the Cloudflare Dashboard.",
        doc_url: "https://developers.cloudflare.com/bots/get-started/free/",
    },
    RuleDefinition {
        id: "CF-RATE-001",
        name: "RateLimitingNotConfigured",
        category: RuleCategory::WafSecurity,
        default_severity: RiskLevel::Low,
        title: "No Rate Limiting Rules Configured",
        description: "No rate limiting rules are configured for this zone. Critical endpoints (e.g. login, search, APIs) may be susceptible to brute force or Layer 7 DoS attacks.",
        remediation: "Configure rate limiting rules for authentication, API, and sensitive endpoints under Security > WAF > Rate Limiting.",
        doc_url: "https://developers.cloudflare.com/waf/rate-limiting-rules/",
    },
    RuleDefinition {
        id: "CF-DNS-001",
        name: "DnssecDisabled",
        category: RuleCategory::Dnssec,
        default_severity: RiskLevel::Medium,
        title: "DNSSEC Not Enabled",
        description: "DNSSEC (Domain Name System Security Extensions) is disabled or inactive. Domain resolution is susceptible to DNS cache poisoning and spoofing.",
        remediation: "Enable DNSSEC under DNS > Settings > Enable DNSSEC and add the DS record to your domain registrar.",
        doc_url: "https://developers.cloudflare.com/dns/dnssec/",
    },
    RuleDefinition {
        id: "CF-SEC-001",
        name: "PermissiveIpAccessRule",
        category: RuleCategory::AccessControl,
        default_severity: RiskLevel::Critical,
        title: "Overly Permissive IP Access Rule (0.0.0.0/0 or Wildcard Whitelist)",
        description: "An IP Access Rule or Firewall Rule is configured to allow or whitelist '0.0.0.0/0', '::/0', or wide subnets, effectively bypassing security controls globally.",
        remediation: "Review Security > WAF > Tools > IP Access Rules and remove any broad allow/whitelist rules for 0.0.0.0/0 or excessive CIDR blocks.",
        doc_url: "https://developers.cloudflare.com/waf/tools/ip-access-rules/",
    },
    RuleDefinition {
        id: "CF-SEC-002",
        name: "InsecureSecurityLevel",
        category: RuleCategory::SecurityLevel,
        default_severity: RiskLevel::High,
        title: "Zone Security Level Set to Ineffective Setting ('Essentially Off' or 'Low')",
        description: "Zone Security Level is set to 'Essentially Off' or 'Low', disabling IP reputation scoring and bot challenge protection.",
        remediation: "Set Security Level to 'Medium' or 'High' under Security > Settings in Cloudflare Dashboard.",
        doc_url: "https://developers.cloudflare.com/waf/reference/security-level/",
    },
    RuleDefinition {
        id: "CF-SEC-003",
        name: "BrowserIntegrityCheckDisabled",
        category: RuleCategory::SecurityLevel,
        default_severity: RiskLevel::Low,
        title: "Browser Integrity Check Disabled",
        description: "Browser Integrity Check is disabled. HTTP headers commonly used by spammers and threat actors will not be challenged.",
        remediation: "Enable 'Browser Integrity Check' under Security > Settings in Cloudflare Dashboard.",
        doc_url: "https://developers.cloudflare.com/waf/reference/browser-integrity-check/",
    },
];

pub fn get_rule_by_id(id: &str) -> Option<&'static RuleDefinition> {
    ALL_RULES.iter().find(|r| r.id == id)
}
